---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    project_7:
      owner: Projectum-7
      repository: project_7
      webhook:
        endpoint: /project_7
        port: "12000"
        method: POST
        url: http://webhook.140.238.216.140.nip.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json

