apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAhpT9kfeUHcNvhVa3dFl6Dp5/d5fZsqFC74ytkUUrJXy285JYCtQ8kX0JpuTtkX0R35NgKERRfjDgTm6e7UcNF0YikxlrSai1kjfXfZkgdOJBzU6usnrtfeR+jM/DtBY/zQdwHF5p05YmTh9Ub7X5Fyvg2bmisHTNlXGm28/D6sR/1oIOCwaNXnSCXkEDdSGni4XD40XgbBYZX8hq4kxvrLZztUyC//yB0eawFZ+F776E2TmJ4J0L9TNQay/0W5XbLWRWPQzI7T5nWDv4dichuz5XzGO/R9d55v3f2y2c65VXL+u/ZSwtUOqZam+MXGaEgQ1S03YqnAsnFpqJQ4TsOmQz100XcxAOj3RV8HlYW7I6SyFCdguT8mgsq1KbmiVCsxi8HrlQ1TejgKtitvd5am53HG7Bl15aCZoHj4g5vqZrY0ic+MharbmCZhEbBed8i2QcMugHGinL13iFxHdTvsR5GiTuzz9D2rGM/8fsziY+f9ggCM7xau9yQ3MVCWcHnL0tBZlZJCHbze8i2OHF5qJ0sDFSTsYcYDsLqYPfpkDZ6vMbM7VkUihjvy0JjgRc5OXJPmJNFsBuKXn1Eour5JUnpNk6w9vyHGg+yKuGyhkPMy7lULmTzpfnX80JPvhJ5slHG44sxg3iBxI5xW8T4ewfEKuJh29/lrEHhuJfnLTaU/sL7M3gav9DIpDwv8kpaao01871yHnXCAgeMNjRZyFYPY+1kDD8FWzGgBuqaSwHO7i1EmU7GiA==
  template:
    metadata:
      name: github-access
      namespace: argo-events
    type: Opaque
