apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBnWOuiC4ssPmpJJ2sJCWxvSJxuv0cGVN4O83o0ZMNGyc7mgLd+ZAXH3R1c6okUiU1cCLwb5ncmzC29lT2udZwyaINo4uk3w6gfmQB8sQyz+tW6fIN4RZB3WwoVEDAoOqqPrBysegELaSUj8FKJqsUEd6JhD8CbSEDP0Gi5NqXTo+oz4q7w/YzFAwxLXMBBha4RByI+uwkmV8T6W6fqCxUct8nf9jLAq9orvII7QF80nbN6EiirWjTbSRSars8OYns3hoch3JO9k/oIBE5vZ1klNlNm5+b85rcNvFXS2PDS5oBsHCpa/WTRdhyn4X0PLmoSB32ny0Ar3NJmAmP7TqjbxAZrXYbSEc59kukHLRPqJIeWDmLjHcDNvVXgZtZG92mrKAgfS3438ONglVI/vjkoChuZYajRTfonjoX1V558SgJ5tsHmcmfLJ8rClSJiWHC2rp3N27EGPlo0eEOxIx5ue8EA93qd4Tk9cYaYMtAv5SCv/lE2+IlxDcRaDip0x+nbUo74wCorYB+d2+/OqaXhxLFdWsc30mXAvYX4ln6iwyZjqRKFsolpia7V6l6ARupET8TubUd0m9Yj2W0e1VAQFmNb6eDN/fXquCNaMRy5o6uldFflHxOecdJS1oy9XhdQSB3oIVkzvwC6LXez9v/AlAW0CVbsYqp9nEqZ5Fn0HopbzolEHqpnOHObrlQvjR3N/vEN3rzQZvjzwpG1HoXrIR294EW3zcaxDlPZts8ctCzEUbbHz6eE
  template:
    metadata:
      name: github-access
      namespace: argo-events
    type: Opaque