apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- github-api-token.yaml
- event-sources.yaml
- sensors.yaml
- ingress.yaml
patchesStrategicMerge:
- patch-nats-streaming.yaml
namespace: argo-events
