apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github
    eventSourceName: github
    eventName: project-7
    filters:
      data:
        - path: headers.X-Github-Event.0
          type: string
          value:
            - "push"
        - path: body.ref
          type: string
          value:
            - "refs/heads/main"
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: project-7-push-to-master
              namespace: argo-workflows
            spec:
              entrypoint: build
              serviceAccountName: workflow
              volumes:
              - name: regcred
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: ssh-config
                configMap:
                  name: argo-workflows-ssh-config
              - name: ssh-keys
                secret:
                  secretName: project-7-deploy-key-secret
                  defaultMode: 0400
                  items:
                  - key: ssh-privatekey
                    path: id_ed25519
              templates:
              - name: build
                dag:
                  tasks:
                  # - name: build
                  #   templateRef:
                  #     name: container-image
                  #     template: build-kaniko-git
                  #     clusterScope: true
                  #   arguments:
                  #     parameters:
                  #     - name: repo_url
                  #       value: ""
                  #     - name: repo_ref
                  #       value: ""
                  #     - name: repo_commit_id
                  #       value: ""
                  #     - name: container_image
                  #       value: "enyediaz/"
                  #     - name: container_tag
                  #       value: ""
                  - name: promote-production
                    templateRef:
                      name: promote
                      template: promote
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: environment
                        value: production
                      - name: repo_ssh_url
                        value: ""
                      - name: image_owner
                        value: enyediaz
                      - name: image_name
                        value: ""
                      - name: tag
                        value: ""
                    # dependencies:
                    # - build
        parameters:
        # - src:
        #     dependencyName: github
        #     dataKey: body.repository.git_url
        #   dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
        # - src:
        #     dependencyName: github
        #     dataKey: body.ref
        #   dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
        # - src:
        #     dependencyName: github
        #     dataKey: body.after
        #   dest: spec.templates.0.dag.tasks.0.arguments.parameters.2.value
        # - src:
        #     dependencyName: github
        #     dataKey: body.repository.name
        #   dest: spec.templates.0.dag.tasks.0.arguments.parameters.3.value
        #   operation: append
        # - src:
        #     dependencyName: github
        #     dataKey: body.after
        #   dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
        - src:
            dependencyName: github
            dataKey: body.repository.ssh_url
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
        - src:
            dependencyName: github
            dataKey: body.repository.name
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.3.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
