apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-7
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Projectum-7/project-7'
    path: kustomize/overlays/production
    targetRevision: HEAD
    kustomize:
      images:
      - enyediaz/project-7:0cc950b1f4ae570e5a754251bbaa34925dfdf235
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
