apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-7
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Projectum-7/project-7'
    path: kustomize/overlays/production
    targetRevision: HEAD
    kustomize:
      images:
      - enyediaz/project-7:91a9f4f8c8edd91077a504795c546912bdc49ffb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
