apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/argoproj/argocd
  newName: veresij/argo-cd
  newTag: v2.1.0arm64
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.0/manifests/install.yaml
namespace: argocd
