apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: project-7-infra-deploy-key-secret
  namespace: argo-workflows
spec:
  encryptedData:
    ssh-privatekey: AgAPugXMEe+jfW/VZjDC9M4OspMrD+vemFNTrXnYYOtuo9ydJ54NXJ4R5gXnHCGIexR70wYaWYeesBNSAt1hrwJ1Jvc9za2Ep3oLiWc3SX17ZEqattP13T32jTnHYfl23MGWfoCb0LxQREqMZRvDr5HVbUvm8Y+5GWn+BsOEnpBdRwSJjKibpCXG7tQYVaDg31S8cg/JBWQRCdbThdpGhgD7dQ1iWJzVpYuUnPbTT7YiWL/bet1P6RYxuuePvNO3jbiH5lJJs14n4aBfbMeGLvNVTpgnKxunJA2LTMHleSEuIjaDqpTnjyvtTpeGdBYP4In3dDAkBSENZqswSFMdfTDJgRuYtmzZ6hs31OUTbNC7LTtEmY2/+QmVwXGOP6o+GSpIsZ8brRxpUBqcaVvcrprUx7ZAE1IcgNsebyNb0wnmAb9QTAdYdadSGcqpbrjh7hFSeBYVExKh/MTCuX+8A34oKLRqPDADENTEr2AP5zVQ8HMDQNk6ZWrl3s/F6xHDErxUTjrdfsEQTlra43I5u/OzwMowXr14SairIVWq6ZURSW3U/A7AqF/HGxi/SUwSat6WnWtwBS3rlw5Jz7dJQ5vN/RGhc63CBbSIHkJZoreBwVDYrCcPJnfWlAuoIMr7qOAd7mgTbnXMzolSRHETsiht/2QQaEO91qljQ7IClj42nOcx/V36quGl4/flBpcXNKZ1z/3BFU8Xgf18mC+uNsn3wunqtBLS421znwa0BwOLSG44dKqp8YWhsaqo9PMwa6Cm7h4UUAWVnyhDKpeoRImEHMOo1HBcoJuVg4YktBBlhRkZj+345LTOP/Za2ObaCqu3HwLeVJmde5vQlisguF8z5zhk3LSTfj06qKPskmNqFAP9WzsqAtlAuvSslZQUpRIhdaX8XAR/bhx4YmtGOjZlK+6v4qnvbXSbmUDtmPj11PX6bppGyplO3p3pkK3nBJ+BbddVHlNroGkX/770qGerxEnoKta1443xJ3z18UdEfKrvc98fO4RTbGyYxxOCicjmuWKA7mnQbspxv/G1PMmaTYZJ9KWMSTJixCG39F9AULyjKgDB8XIAqkCuY5eT62fHQ7GBvUSoBfzASdxnAJIf5P4Yky3sB84Dlszg/sl+McOVovbY9Uu4GUjOQBOOZiad6/d6KKhYwJZ02kjoAK7PymC7fF/9JtaxSQPQmPbMbP3WRPrkoY6KRPekrMy0E0p+M7WWJa5t0B3DwxliZbIGT0rdDMLZrjjBxjFEWEMlF+kKkQ==
  template:
    metadata:
      name: project-7-infra-deploy-key-secret
      namespace: argo-workflows
    type: kubernetes.io/ssh-auth
