apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: argo-workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCK5ayMRkm4tKQHXd+iVH+Tv1FH833cZWZmZFGAwnIJSzPk+bSg0dOHqVEvG4eTmtyAlpRxekHYxC2m+fxHMefCyTtkXnNAkIZ6k1A336A0nFwQM+nT80vHif75xyZYUljdqR4ZLrpeGhxKQFvjm4bEIwtMxu0Wn/3xGIpk/3ttjHmhlhf92PonSku0Oe8g5gwIOpYtIdUwn/L1Z8OuEqiWRi1kFldzg3lrsaFM5W7gU3tL/lTW44Nawg+oYLYEb+LVqgGrPZ3RG2Vq09j/XE6THv+iEWQLNE88XvlFXHoXEOyVXkXJ+hFi93+FBYsETCuZqzD0xjbyVIOjwGjMBNLr1WvXcRuIxGzM5c6JEeqLP0LKCwAHtmdZeoeFsFXGYCWWz8zR29foNsgcM86oMI4Yr51J0RW3WT5x4zIfS1NX/s67qjzrkNLKTQBJNeFd6u9D0c03X2YNhnfBry918BYbjk+eO2shFoIG3kjJc8meJK/vajv47/wkjjl0WALCABQEFtEPhAJISIGb/CbL0IEQmjB2uBhskfVVGtoqh5lN05yjIVFdmOTCi2SA8o2WFqAqkA6ZWhoNg5vTgg+eLu+nK7nacJLEy9Ybv+QuizIc0f6eM6cLVUgLNzQeNO35jeG5bwOU1iJZhUO/RYyPSf5OJtcEEmfzhvqsvszNsKE3TUEHMgCCDYdv6lBNPHUfd3VmwSDwzwndCvoTfKG0VqiHNOt/U8vyp2eKtOtF37HFGLTNYdhCVwSej0sI9G8HviJnNkX5/UNWH4m3k2ePaKnpW3DUivPWD/rP73Qug48RYToe/ChY8TTIoAR9LDpJbaToYic8yBlICjZ1RerwzkLzbbA12q7syw7DD22KQdkQOXvugJ926ZgAbRp45bwfYJotbYMyRO2iBM/Tzr6PIGTbTamALdwnLNstcOG9Q8dP1w/UTRLLjM4xFg3dbeb0iVMtM+zTlA6qWMk+gRiy7lRZ3fGIgr+V
  template:
    metadata:
      name: regcred
      namespace: argo-workflows
    type: kubernetes.io/dockerconfigjson
