apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCEOfdubaf1PbDcPi6V7aMCc6OZBh6hQTTsrOkoV0HBh8YnF0wsUNUzeOp2VkDYXDLyp+tsqYVRI43Rfqm1aln2SxGXdfhtrhzKm9rxriC/pNVFoFsefQxrBqDFy9Q+EGWx/s7iYgixdIeiAH8x6Gu7cw6TNgJKvHPIK3WDYvS+bH20JjtFPcqqOPVssUOz6sg22f8G/M9sKnESoEdhtq+VNgk8PfoLrjM9VZM3kR4us8P7CRB+lmAw0XxgbU5PcRpKHvd7F9Ke5BXiVZh6pBRftjZW9yfLI5aEr92MrrNpkbjCbDA2CeWjywaAZRaSIGrW7ixJN7uLQvXp1QnU/tLtyaT806cf80PsmhJMCtrF2VD9Dwg9wI7NXh9WC6uOm7yHtC00+u6pRd+40+aT6g+r5Xxa9avr6JO4olMIrjy/E8O5341xtCdx+MTGyLTLCVYYxsybHJq1tRL5HI8Xi4fngPZB4BNHdEF9pDYT6sjWkBKs3tG3L299xy49mRhcAFyGdFyoTzYdLX7b2hAJqHwBXnfDxO7DoilfC+CYPy0hvL4ca+C7rvxbxQ0eDQU5gEj6s6ZFRZuoFzqBNU4H1KwUAAGZwGwPPYfEEvjk/SfYMv1ocuaosSFHQzYIoG/MiKCJx1QFV1BH83lsocVWlXk8H1T5NXL4a2aKwY39gb22uK0jXnGxLBWPWAlz666F0nP1AO0w8+3ZVxutT4WIYqLhoevycBFBPzvIC/8Yaz5vfczOg+JN6bFXhB/fsNw4xcHiiA1Ml3sAlXWbm8iYmYEx1ONzstVHTlv8vSJF9/kLHIngZ4lpDIIO4dcGZtksoDeDDZdXaXjknz233agR4mPcqY8vAY2Oe91OczNvlUS2UTFdJl/APL33fOou2WsH2iTqLgxZSUJZBhLp9RSJbrEOSar9PuWIfT8HTSHcO6OsUIVtFIZrvu7L2lJ+lwFeCDPeDjhvCpYV0dLdxLAhbGE99DsowXXO
  template:
    metadata:
      name: regcred
    type: kubernetes.io/dockerconfigjson